# Generated by Django 6.0.4 on 2026-04-08 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('provider_key', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('card', 'Card'), ('loan', 'Loan'), ('biller', 'Biller')], max_length=20)),
                ('external_account_id', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('masked_number', models.CharField(blank=True, max_length=8)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed'), ('disconnected', 'Disconnected')], db_index=True, default='pending', max_length=20)),
                ('oauth_access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.financialinstitution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'account_type'], name='accounts_li_user_id_11efff_idx'), models.Index(fields=['status', 'updated_at'], name='accounts_li_status_a40ba6_idx')],
                'unique_together': {('user', 'external_account_id')},
            },
        ),
    ]
