# Generated by Django 6.0.4 on 2026-04-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creditor_name', models.CharField(max_length=255)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('minimum_due', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('missed', 'Missed')], db_index=True, default='upcoming', max_length=20)),
                ('auto_pay_enabled', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_dues', to='accounts.linkedaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'due_date'], name='accounts_pa_account_9770bf_idx'), models.Index(fields=['status', 'due_date'], name='accounts_pa_status_4b9f01_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_transaction_id', models.CharField(db_index=True, max_length=255)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('payment', 'Payment'), ('fee', 'Fee'), ('interest', 'Interest'), ('transfer', 'Transfer')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='posted', max_length=20)),
                ('transaction_date', models.DateField(db_index=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.linkedaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'transaction_date'], name='accounts_tr_account_3b8440_idx'), models.Index(fields=['account', 'transaction_type', 'transaction_date'], name='accounts_tr_account_685e14_idx')],
                'unique_together': {('account', 'external_transaction_id')},
            },
        ),
    ]
