# Generated by Django 6.0.4 on 2026-04-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_auth_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.CharField(choices=[('registered', 'Registered'), ('phone_verified', 'Phone Verified'), ('accounts_connected', 'Accounts Connected'), ('cards_confirmed', 'Cards Confirmed'), ('bills_added', 'Bills Added'), ('analysis_complete', 'Analysis Complete'), ('completed', 'Completed')], db_index=True, default='registered', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(blank=True, default='+1', max_length=5, verbose_name='country code'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
