# Generated by Django 6.0.4 on 2026-04-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_paymentdue_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('user', 'User'), ('account', 'Account'), ('debt', 'Debt'), ('bill', 'Bill'), ('creditor', 'Creditor')], db_index=True, max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('owes', 'Owes'), ('pays', 'Pays'), ('guarantees', 'Guarantees'), ('linked_to', 'Linked To')], db_index=True, max_length=30)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_edges', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='credit_graph.creditnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='credit_graph.creditnode')),
            ],
        ),
        migrations.AddIndex(
            model_name='creditnode',
            index=models.Index(fields=['user', 'node_type'], name='credit_grap_user_id_453bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnode',
            index=models.Index(fields=['user', 'external_id'], name='credit_grap_user_id_f2b095_idx'),
        ),
        migrations.AddIndex(
            model_name='creditedge',
            index=models.Index(fields=['user', 'relation_type'], name='credit_grap_user_id_eb7e7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='creditedge',
            unique_together={('source', 'target', 'relation_type')},
        ),
    ]
