# Generated by Django 6.0.4 on 2026-04-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_type', models.CharField(choices=[('intervention', 'Intervention Impact'), ('what_if', 'What-If Scenario'), ('forecast', 'Score Forecast')], db_index=True, default='intervention', max_length=20)),
                ('current_score', models.PositiveSmallIntegerField()),
                ('projected_score', models.PositiveSmallIntegerField()),
                ('best_case_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('worst_case_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avoided_damage_points', models.PositiveSmallIntegerField(default=0)),
                ('score_factors_breakdown', models.JSONField(blank=True, default=dict)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('horizon_days', models.PositiveIntegerField(default=90)),
                ('model_version', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interventions.intervention')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
