# Generated by Django 6.0.4 on 2026-04-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FallbackPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('direct_pay', 'Direct Pay'), ('bnpl', 'Buy Now Pay Later'), ('installment', 'Installment Plan')], db_index=True, default='direct_pay', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_installments', models.PositiveSmallIntegerField(default=1)),
                ('bnpl_provider', models.CharField(blank=True, max_length=100)),
                ('bnpl_reference', models.CharField(blank=True, max_length=255)),
                ('repayment_start_date', models.DateField(blank=True, null=True)),
                ('total_repayable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_provider_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('settled', 'Settled'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_payment', to='interventions.intervention')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('defaulted', 'Defaulted')], db_index=True, default='active', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fallback_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedules', to='fallback_payment.fallbackpayment')),
            ],
            options={
                'unique_together': {('fallback_payment', 'installment_number')},
            },
        ),
    ]
