# Generated by Django 6.0.4 on 2026-04-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReportPull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bureau', models.CharField(choices=[('experian', 'Experian'), ('equifax', 'Equifax'), ('transunion', 'TransUnion')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('raw_report', models.JSONField(blank=True, default=dict)),
                ('score_at_pull', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_accounts', models.PositiveIntegerField(default=0)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('open_collections', models.PositiveIntegerField(default=0)),
                ('derogatory_marks', models.PositiveIntegerField(default=0)),
                ('hard_inquiries', models.PositiveIntegerField(default=0)),
                ('credit_utilization', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('oldest_account_date', models.DateField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('pulled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_report_pulls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bureau_source', models.CharField(max_length=50)),
                ('credit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('risk_summary', models.TextField(blank=True)),
                ('detected_errors', models.JSONField(blank=True, default=list)),
                ('improvement_opportunities', models.JSONField(blank=True, default=list)),
                ('estimated_score_gain', models.PositiveSmallIntegerField(default=0)),
                ('model_version', models.CharField(db_index=True, max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_analyses', to=settings.AUTH_USER_MODEL)),
                ('report_pull', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='ai_engine.creditreportpull')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField(default=90)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('plan_data', models.JSONField(blank=True, default=dict)),
                ('generated_by_model', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.creditanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='creditreportpull',
            index=models.Index(fields=['user', 'bureau', 'pulled_at'], name='ai_engine_c_user_id_13dce8_idx'),
        ),
        migrations.AddIndex(
            model_name='creditanalysis',
            index=models.Index(fields=['user', 'generated_at'], name='ai_engine_c_user_id_d8fb90_idx'),
        ),
    ]
